---
- name: Deprovision cloud server
  hosts: localhost

  vars:
    cloud_provider: "{{ lookup('ansible.builtin.env', 'CLOUD_PROVIDER', default='') }}"

  tasks:
    - name: Deprovision cloud server
      ansible.builtin.include_role:
        name: ryankwilliams.aap_toolbox.vm
        tasks_from: delete
